### ISSUE TITLE
When a job with retry set to 0 gets dequeued, it should be removed.

### ISSUE THREAD

**Issue by antirez** [antirez/disque#1]
We are sure the job will never be requeued again, since it is against the retry parameter set to 0, meaning the user requested the _at most once_ semantics. Waiting for an ACK for this job is probably silly, we should just remove the job as soon as we transmit it to the client.

**Comment by justincase** [comment]
By removing the job after it's been transmitted, we lose access to the job's metadata from `SHOW <job-id>`. For example, `GETJOB` does not return `ctime` which is needed to determine the age of a job.

**Comment by antirez** [comment]
@justincase yep that's true... we miss the ability to inspect the job in the Disque side, but then if it's a fire and forget job... do we really want to retain this information? Or fire and forget jobs will likely have a short TTL so this is acceptable? Or maybe we should retain those jobs, but evict them in `freeMemoryIfNeeded()` like ACKs when we are short on memory? The last one sounds sensible, so if there is free memory, we use it to retain more state.

About `GETJOB` not returning those info, there is the idea to augment GETJOB with more options so that you can get a number of information about a job, including ctime, the count of retries and NACKs (when available), and so forth. So this is going to be solved in a direct way... :-)

**Comment by justincase** [comment]
I like the idea of GETJOB optionally returning the job's metadata. That way the job itself can be discarded right away without the need to retain anything.

**Comment by antirez** [comment]
Quick update on the issue. So currently best solution apparently is:
1. If memory warning is > 0 (75% of more used), discard at-most-once delivery jobs ASAP when they are returned by `GETJOB`.
2. Once there is to evict data in `freeMemoryIfNeed()` we discard those jobs to reclaim memory.
3. However I would also add an option to discard at-moce-once jobs ASAP in all the cases for people that don't care much about observability of that jobs and want a more vanilla memory behavior. This would go in the _advanced_ section of `disque.conf` anyway.

**Comment by antirez** [comment]
In the above discussion there is an important missing part, which is, if we discard the job having retry set to 0, and the client acknowledges it anyway, currently what happens is that the node receiving the `ACKJOB` of a job it does not know, will create a _dummy ack_. It cannot know the ack is about a job with retry set to 0. This will trigger a cluster-wide GC attempt.

So there are a few solutions:
1. Retain the jobs and only evict them on critical memory issues in `freeMemoryIfNeeded()`.
2. Put in some way the retry policy inside the job ID, so that receiving nodes know about the fact there is no need to create a dummy ack.
3. It's a bit of a shame that retry 0 jobs must be ACKnowledged explicitly at all, so we may also return the retry count alongside with the job in GETJOB. This way if a job as retry set to 0, the client should not ACK it. However this makes the API more complex, and fire and forget workload may be less important then expected with Disque.

**Comment by antirez** [comment]
Ok my latest take on this, until implementation or next change of idea:
1. Retain jobs, so that the workflow is identical whatever the job kind is, from the POV of clients.
2. Evict those jobs when we are short on memory, since they are irrelevant if lost, and there is not the problem of leaking them otherwise.

However in addition to that, it would be kinda nice to also have a one bit flag in the node ID signaling this job is a fire-and-forget one. This way we could avoid the creation of a dummy ack. Not sure where to put this currently.

**Comment by antirez** [comment]
Finally fixed the first issue ever opened :-)
