### ISSUE TITLE
cluster meet not working

### ISSUE THREAD

**Issue by pulse00** [antirez/disque#116]
I'm trying to follow the README to setup a cluster of 2 disque nodes on 2 amazon ec2 instances. When i run `disque cluster meet <IP> <PORT>` disque replies with `OK`, but it seems no clustering has been setup.

The logs on the second node do not show anything and when i do `ADDJOB queue body 0` on `node1` and `GETJOB FROM queue` on `node2` there's no job in the queue.

Am i missing something obvious here?

**Comment by pulse00** [comment]
It seems the nodes communicate on port `17711`, so after adding an appropriate firewall rule the clustering worked. Is this configurable somehow? I'd be happy to contribute to the docs if i understand properly how it's setup.

**Comment by antirez** [comment]
Thank you @pulse00, doc updated. The offset is fixed at `baseport+10000`.
