### ISSUE TITLE
Approximate ETA for beta release

### ISSUE THREAD

**Issue by skyrocknroll** [antirez/disque#131]
Hi , 
Right now we are using redis for message queuing. We want to move to queuing system which supports better queue sematics like alleast one delivery and delayed messages. 

It would be great is there any approximate timeline when disque will be released to beta stage.

**Comment by misiek08** [comment]
You can achieve one delivery and delayed messages in redis. Just write LUA scripts and you will have production-ready solution.

**Comment by mathieulongtin** [comment]
Or just use qless

**Comment by skyrocknroll** [comment]
1.0 RC1 is out
http://antirez.com/news/100
