### ISSUE TITLE
How do you want it pronounced?

### ISSUE THREAD

**Issue by davidascher** [antirez/disque#136]
Disque is a French word, meaning disc.  Pronounced as a single syllable (the `ue` is silent). However, it's not nearly as punny as if it's pronounced dis-queue.  So enqueuing minds want to know: how do you think it should be pronounced?

Congrats on the RC1.

**Comment by itamarhaber** [comment]
This isn't really an issue, but the latter: https://youtu.be/GRuFG7QVvCY?t=34s

**Comment by antirez** [comment]
Thanks, it's needed like `dis` as in distributed + `queue`.
