### ISSUE TITLE
How to completely delete a job?

### ISSUE THREAD

**Issue by evanhuang8** [antirez/disque#172]
It seems that `DELJOB` only deletes the job from one instance of `disque`, so does that mean that I will need to connect to every single instance in the cluster and issue `DELJOB`? is there any reason why DELJOB is not part of the gossip?

**Comment by themage** [comment]
@evanhuang8, doesn't ACKJOB do what you need?

from the source comments, DELJOB seems to be more of a debug util than part of normal queue operation.
