### ISSUE TITLE
Getting 0 jobs out of a non-empty queue succeeds

### ISSUE THREAD

**Issue by jlouis** [antirez/disque#25]
This is another counterexample I found, where I'm breaking the rules of disque:

```
[jlouis@lady-of-pain disque]$ ./src/disque addjob test_queue foo 5000
DId886465d76d7924aa56a785240a182dd0f80af0505a0SQ
[jlouis@lady-of-pain disque]$ ./src/disque getjob count 0 from test_queue
1) 1) "test_queue"
   2) "DId886465d76d7924aa56a785240a182dd0f80af0505a0SQ"
   3) "foo"
```

I would have expected an error because I'm supplying a COUNT < 1, which is a violation of the specification. Hence, I'm reporting this as something the parser perhaps should disallow rather than accept as if it was COUNT 1.

**Comment by antirez** [comment]
Yep definitely a bug. It should return an error or an empty array. Probably the error is more appropriate since it does not make a lot of sense to fetch zero jobs, likely a bug in the application logic.
