### ISSUE TITLE
In a 2-node setup, QPEEK doesn't see the queue contents of the "other" node

### ISSUE THREAD

**Issue by jlouis** [antirez/disque#33]
The setup is that we have two nodes on localhost, 7711 and 7712 ports, standard configuration. We add a job on 7711 (with replication factor 2) and QPEEK on 7712:

```
[jlouis@lady-of-pain disque]$ ./src/disque -p 7711 cluster meet "127.0.0.1" 7712
OK
[jlouis@lady-of-pain disque]$ ./src/disque -p 7711 addjob test_queue x 300 replicate 2
DId28925cea079cee4507e3904ab7b85d2f979a72c05a0SQ
[jlouis@lady-of-pain disque]$ ./src/disque -p 7712 qpeek test_queue 1
(empty list or set)
[jlouis@lady-of-pain disque]$ ./src/disque -p 7711 qpeek test_queue 1
1) 1) "DId28925cea079cee4507e3904ab7b85d2f979a72c05a0SQ"
   2) "x"
```

The output of the empty queue on 7712 is not what I expected. I expected a result as 7711's query in the end. Is this a bug or a feature? Running QLEN shows the same discrepancy:

```
[jlouis@lady-of-pain disque]$ ./src/disque -p 7711 qlen test_queue
(integer) 1
[jlouis@lady-of-pain disque]$ ./src/disque -p 7712 qlen test_queue
(integer) 0
```

Again, bug or feature?

**Comment by justincase** [comment]
It's a feature.

> 1. A job is replicated to multiple nodes, but usually only queued in a single node. There is a difference between having a job in memory, and queueing it for delivery.

Running `SHOW <job-id>` on both nodes will show you the state of the job on that node.

> `job.state`: The job state among: `wait-repl`, `active`, `queued`, `acknowledged`.
> 
> States are as follows:
> 1. `wait-repl`: the job is waiting to be synchronously replicated.
> 2. `active`: the job is active, either it reached the replication factor in the originating node, or it was created because the node received an `ADDJOB` message from another node.
> 3. `queued`: the job is active and also is pending into a queue in this node.
> 4. `acknowledged`: the job is no longer actived since a client confirmed the reception using the `ACKJOB` command or another Disque node sent a `SETACK` message for the job.

**Comment by antirez** [comment]
Yep, indeed it's a _feature_. `QPEEK` is a debugging command useful to investigate the state of each node: to trigger jobs passing between nodes as side effect would be definitely an issue.

**Comment by jlouis** [comment]
Same with `QLEN` ?

**Comment by antirez** [comment]
Exactly, both are local commands. Similarly the MAXLEN option of ADDJOB is local as well. Note that a QLEN variant that would return the total cluster-wide length must do the same work as the client querying each single server, since Disque distributed nature does not prevent any node of the cluster from having some job about a given queue.
