### ISSUE TITLE
Graceful exit of node from cluster

### ISSUE THREAD

**Issue by antirez** [antirez/disque#60]
Ability to mark of a given node as _leaving_:
1. It's a node flag, so gets propagated cluster-wide with current cluster gossip features.
2. When a node is flagged as _leaving_ it does no longer creates local messages. It handles `ADDJOB` requests using external replication and `ACKJOB` never creates dummy acks.
3. The node refuses to accept new messages from the cluster as well, but also the other nodes avoid to try to replicate new messages into it directly. So no new messages are ever added to exiting nodes.
4. The node is otherwise part of the cluster: can work as a source of messages for other nodes, participates in acknowledging messages and so forth.
5. HELLO command node priority is set to a low value so that clients start to avoid using it.
6. Clients that would block on `GETJOB` are sent a `-LEAVING` error instead.
7. Clients already blocked are unblocked with a `-LEAVING` error.

Eventually a node in this state reaches a number of jobs of zero, and can be removed from the cluster entirely. This allows Disque clusters to be migrated into a different set of servers without any interruption of service.

Normally this is not needed in order to remove a node from a cluster (but still can be used for this goal), since to shutdown the node is enough because the messages are replicated into other nodes as well.
However using this feature, it is possible to remove a node without effectively lowering the number of copies of a set of messages.

The feature is exposed as a CLUSTER LEAVING command.

The behavior of the other nodes is to always replicate this bit in their configuration, using as the source the node itself. So if a node advertises itself with the `leaving` flag set, all the other nodes will set the flag. If the flag is no longer set, all the other nodes will clear the flag.

**Comment by romankl** [comment]
Do you mind, if I could take a look at this one? Or is it already assigned/ in work?

**Comment by antirez** [comment]
Implemented (in a more complex / better form than the original proposal. Now the proposal is updated). Documentation in progress.

**Comment by antirez** [comment]
Full set of commits implementing this:

719df8f CLUSTER LEAVING improved.
58c0941 Fix external replication bug due to premature cleanup.
9ddd06d Graceful leaving the cluster with CLUSTER LEAVING.
