### ISSUE TITLE
NACK and dead letters, recap and proposal

### ISSUE THREAD

**Issue by antirez** [antirez/disque#68]
In other message systems, especially the ones used to process asynchronous tasks, people are used to two features: negative acknowledgements and dead letter queues.

The role of NACKs is make workers able to actively signal a job as impossible to process, with two main benefits:
1. Make the job available for other workers to process it ASAP, without the need to way the _retry_ time.
2. Provide a semantical hint about the lack of ability to process the job, that is, information about _why_ a job was not able to be processed, and ability to distinguish a message that gets lost from a message that is not processable because of its content.

Another feature closely related is _dead letter_ queues: a place where jobs that are impossible to be processed go, for later inspection.

During the weekend I tried to understand if there is a way to avoid to have dead letter queues without, after all, making Disque less functional. There is something disturbingly bloatware in this feature in some way, yet it is very important for the application to be notified that there are jobs that can't be processed. However maybe it is possible to just provide minimal help to the application using Disque to handle failures?

So that was my design assignment for the weekend, and this is my proposal.

Disque will add a `NACK` command, very similar to `ENQUEUE`, that is, the command will try to put the message back into the queue ASAP for other workers to process. However there are two things that Disque will track.
1. A best effort count of the number of times the message was delivered _after_ the first time. That is, the amount of additional deliveries. This count is best effort and is not guaranteed to be consistent across nodes. However this should not be an issue in this context (read more).
2. A best effort count of the number of times the message was NACK-ed.

When using `GETJOB`, the worker can pass an option to also retrieve these two counters. The application can decide to do anything with them. For example: if the number of NACKs is greater than 3 the worker may add the job in a _dead letter_ queue (but note that this is not implemented by Disque, is just what the worker decided to do). The worker may actually try to process the job and provide additional information in the dead letter if it wishes, like stack traces or alike.

Workers implementing a dead letter may do interesting things like setting the replication factor to 1, specifying MAXLEN option and so forth, depending on the application needs, in order to avoid dead letters to turn into an auto inflicted DOS :-) Workers may even `FASTACK` the original message when doing so, in order to avoid other workers to waste time with the same job.

Otherwise the worker may just provide some warning in other form to the application, like to the monitoring system, when it sees too many re-deliveries of the same job or alike. The bottom line here is **it is up to the application** what to do.

The missing part about this is a dead letter for jobs reaching the TTL. I've a _semantical issue_ with that. If a job is never processed within the TTL, and you want to log it somewhere _inside_ the system, then you really want a different TTL: you are not ready to lose the job after the expiration time you proposed elapsed.

The only justification for the above feature is IMHO outside the message safety context, since the TTL should specify a time after which processing the job is no longer useful. So the left reason is actually debugging. However for debugging tasks, I've the feeling most users could be happy enough just with Disque logging the event in a log file where all the unprocessed jobs expired by TTL go.

Additionally Disque could provide an API to access the latest N items inside the file (in a way that does not allow the process to block, i.e. using a different thread that populates an in-memory version of the data from time to time, like: file size, last N items, and so forth).

I believe this gives us 99% of what dead letters provide, but without making the Disque design more complex... Feedbacks appreciated.

**Implementation details**

The counters would just be approximated, if there are partitions and we lose one increment, the next re-queue the counter will eventually reach the threshold for the application to be warned about the inability to process the job. So basically every node would have in their private `job` object the two counters, incremented in the following ways:
1. When a QUEUED cluster bus message is received, the number of additional deliveries is incremented. The message is sent to all the nodes that have a copy according to the node putting the job back in queue again (but not the first time a job is queued).
2. When a NACK is received, the QUEUED message broadcasted will be flagged in a way that forces the receivers to increment the nack counter instead. So it's the same system as in the previous item. We just take two counters to distinguish between messages lost for other causes, and messages actively NACKed.

**Comment by sheerun** [comment]
Can't workers increment counter by themselves? Disque'd need just additional `REQUEUE` command that requeues given job, and allows to add extra metadata. Something like:

```
REQUEUE <job-id> SET retry 2 SET stacktrace "xxx yyy"
```

I guess no new cluster messages are necessary with this.

**Comment by VojtechVitek** [comment]
Do I understand the flow correctly?

Worker:
1. `GETJOB`
2. ...processes the job...
3. **on failure**:
4. parse `num_of_NACKs` from `SHOW <job-id>`
5. if `num_of_NACKs >= 5`
   - then `ADDJOB dead_letter_queue` && `FASTACK <job-id>`
   - else `NACK <job-id>`

**Comment by antirez** [comment]
@sheerun not worth putting additional work to clients (as you can see there is a clear design idea in Disque to be kinda of magic from the POV of the clients, more or less the contrary than Redis, and for specific reasons). Basically the new message is dispatched to an existing message, that is already covered by two different names, and will only increment a counter other than doing the usual work, so very little actual complexity.

@VojtechVitek No is a bit different, you get the two counter values from `GETJOB` itself if you want (specifying an option). So when you get the job, if it is already one with an high number of failures, you can act ASAP, or try to process it just to understand why it fails and post a stack trace in a dead letter queues, or whatever.

**Comment by Revisor** [comment]
Let's say I have a queue `emails` and a corresponding dead letter queue `failed-emails`. Something went wrong and now I have a job with `allowed-failure-count < nack-count + additional-delivery-count`. Each failure generated an entry in the log.

Would it make sense and would it be useful to move the job to the `failed-emails` queue while keeping its job ID, `nacks` and `additional-deliveries`? Keeping this information would help pairing log entries with the job.

Of course there is always the possibility to add meta information to the job's body. But judging from the comments eg. about Resque 2.0 wishes ([1](https://github.com/resque/resque/wiki/Failures-2.0), [2](https://github.com/resque/resque/wiki/Job-MetaData-2.0)), people want more metadata, not less. So keeping whatever metadata Disque supports natively even when "burying" a job (to borrow terminology from beanstalkd) might be helpful.

**Comment by antirez** [comment]
Helo @Revisor, you can of course: before creating your new job it is possible to use "SHOW" or any other introspection mechanism in order to get the full details of the original job, and create a new job that represents the failure of the old job with all the details. I don't think it's a good idea to try to crete the failed job with the same job ID, because of the immutability concept in Disque jobs. It only makes design more complex. Moreover often you may want to add a backtrace of the bug from the POV of the worker in the failure report, so the body is going to be different as well.

Closing this issue since everything described here is implemented and documented at this point. Thanks everybody.
