### ISSUE TITLE
Configurable QUEUE_MAX_IDLE_TIME

### ISSUE THREAD

**Issue by justincase** [antirez/disque#77]
With many transient queues it would be helpful if the GC interval (`QUEUE_MAX_IDLE_TIME`) was configurable in the configuration file and possibly with `CONFIG SET`. This in order to more aggressively clean up obsolete queues.

**Comment by r-52** [comment]
Do you know an example, where it could be useful to customize the GC? 
The GC should only free queues that are empty, have no clients in the list and reached the idle time, so they are basically "at the moment" dead memory. Setting it in the configuration file could be useful, but it could be too broad for all queues. Lets say we define a very high queue idle time in the config and our connected client creates a lot of unique queues, where each job is nearly instantly acked. That would result in a lot of dead memory till the idle time is reached. To avoid such a scenario there are ways like:
- max idle time per queue
  - Each queue has the configured max idle time after its creation and the client can upper or lower the idle time.

and a not so great way:
- clients are responsible to destroy idle queues like manually memory management

**Comment by justincase** [comment]
@romankl Exactly that; volatile queues with one-off jobs. For example, a worker might listen for jobs on a specific endpoint as part of a request/reply chain. Granted, this leans more towards a message queue but a configurable GC wouldn't be that invasive.

**Comment by antirez** [comment]
Possibly simpler solution:
1. Free idle queues in `freeMemoryIfNeeded`. This is called when we are at 95% of maxmemory.
2. Use a very short QUEUE_MAX_IDLE_TIME in `GCQueue` called by `queueCron`, when getMemoryWarning is > 0 (starting at 75% of maxmemory).

This way it's kinda adaptive to the situation, and if there are plenty of short living queues, the memory is reclaimed anyway when it starts to be an issue.
