### ISSUE TITLE
Code errors discovered by static analysis

### ISSUE THREAD

**Issue by bos** [antirez/disque#81]
I've run a static analyzer over `master` (b5264359ddf0aa04a49b921c383c49ded7e7eea6 at the time of writing), and found some problems with memory management. They all involve failure to check the results of memory allocations, so in a low-memory situation, disque is simply going to crash.

`redisAsyncInitialize` may return `NULL`, but its result is not checked.

```
disque/deps/hiredis/async.c:172: error: NULL_DEREFERENCE
  [B1] pointer ac last assigned on line 171 could be null and is dereferenced by call to __redisAsyncCopyError() at line 172, column 5
```

Failures to check result of `malloc`. Perhaps something like an `xmalloc` wrapper would be appropriate.

```
disque/deps/hiredis/dict.c:75: error: NULL_DEREFERENCE
  [B1] pointer ht last assigned on line 74 could be null and is dereferenced by call to _dictInit() at line 75, column 5

disque/deps/hiredis/dict.c:261: error: NULL_DEREFERENCE
  [B1] pointer iter last assigned on line 259 could be null and is dereferenced at line 261, column 5
```

`redisContextInit` may return `NULL`, but its result is not checked.

```
disque/deps/hiredis/hiredis.c:1062: error: NULL_DEREFERENCE
  [B1] pointer c last assigned on line 1061 could be null and is dereferenced at line 1062, column 5
```

It looks like `zrealloc` is simply `realloc`, and its result is not checked for `NULL`.

```
deps/hiredis/sds.c:160: error: NULL_DEREFERENCE
  [B1] pointer sh last assigned on line 159 could be null and is dereferenced at line 160, column 5
```

**Comment by antirez** [comment]
Hello @bos, the allocator used by Disque, `zmalloc`, is designed to abort on out of memory, will never return to the caller if it is not able to allocate, so the above issues are not really going to create problems fortunately. Thanks for running the analyzer!

**Comment by sunheehnus** [comment]
Hi @antirez , I saw the zmalloc in /deps/hiredis/\* is defined as malloc, and there are many direct malloc in the code. :-)
