### ISSUE TITLE
Unable to get disque running on separate docker containers to establish a cluster

### ISSUE THREAD

**Issue by jmontemayor** [antirez/disque#85]
I put together a docker container building disque https://registry.hub.docker.com/u/jobflow/disque/

I am able to deploy and run a single service. I can expose a port and connect to it from a disque client running on the same container or a different container.

But when connect to one instance and send the cluster meet with the ip and port of the other container it will attempt to cluster the instance but eventually fail.

I can link two containers and they will cluster fine, but you can not link a container to more than one. So building a cluster of 3+ isn't working.

I can run multiple disque service in a single container and they will cluster ok. It's just cross container communication that fails.

I wonder if this issue is similar to this one: [Sentinel: Fix initial Hello source address](https://github.com/antirez/redis/pull/1908#issuecomment-54380876)

For more details see:
http://stackoverflow.com/questions/30904033/unable-to-get-docker-containers-running-disque-to-establish-a-cluster

**Comment by andreyvital** [comment]
@jmontemayor any progress since we talked yesterday?

**Comment by antirez** [comment]
I replied into the SO question. Thanks.

**Comment by jmontemayor** [comment]
Thanks, exposing both 7711 and 17711 fixes this.
