### ISSUE TITLE
Support for topic subscription

### ISSUE THREAD

**Issue by smetj** [antirez/disque#94]
- Does/will Disque support consumer pattern-matching subscription to a topic somehow?
  - For example: consume all messages with topic/key "?.cpu.idle"
- Will there be support for fanout/one-to-many messaging patterns?

**Comment by antirez** [comment]
Hello @smetj, the current idea is to limit Disque to the current API, so this excludes one-to-many and pattern matchings. This task is currently kinda served by Redis Pub/Sub, in a fire-and-forget way. However who knows, maybe in the future this may change. For now the idea is to bring the current API to maturity. Thanks!
