### ISSUE TITLE
Expired items queue -- dead letter queue

### ISSUE THREAD

**Issue by skyrocknroll** [antirez/disque#95]
Lets say i have put an item in the queue which causes the worker to crash. so disque re-queue it after RETRY time. Again picked up by the worker . This goes till the job expiry time. When disque expires an job it would be great to have expired job in deadletter queue.

**Comment by badboy** [comment]
#68

**Comment by skyrocknroll** [comment]
https://www.youtube.com/watch?v=GRuFG7QVvCY#t=1143 
Watched this :)
